// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	PriceInCents int64              `json:"priceInCents"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}
