// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package repository

import (
	"context"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permission (role_id, resource, permission_id) VALUES ($1, $2, $3)
`

type AssignPermissionToRoleParams struct {
	RoleID       int32  `json:"roleID"`
	Resource     string `json:"resource"`
	PermissionID int32  `json:"permissionID"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.Resource, arg.PermissionID)
	return err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO "permission" (name) VALUES ($1)
`

func (q *Queries) CreatePermission(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createPermission, name)
	return err
}

const deletePermission = `-- name: DeletePermission :execrows
DELETE FROM "permission" WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, name FROM "permission"
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, name FROM "permission" WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id int32) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
SELECT id, name FROM "permission" WHERE name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i Permission
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.name FROM "permission" p
JOIN role_permission rp ON p.id = rp.permission_id
WHERE rp.role_id = $1 AND rp.resource = $2
`

type GetPermissionsByRoleIDParams struct {
	RoleID   int32  `json:"roleID"`
	Resource string `json:"resource"`
}

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, arg GetPermissionsByRoleIDParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleID, arg.RoleID, arg.Resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByRoleIDAndResource = `-- name: GetPermissionsByRoleIDAndResource :many
SELECT p.id, p.name FROM "permission" p
JOIN role_permission rp ON p.id = rp.permission_id
WHERE rp.role_id = $1 AND rp.resource = $2
`

type GetPermissionsByRoleIDAndResourceParams struct {
	RoleID   int32  `json:"roleID"`
	Resource string `json:"resource"`
}

func (q *Queries) GetPermissionsByRoleIDAndResource(ctx context.Context, arg GetPermissionsByRoleIDAndResourceParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRoleIDAndResource, arg.RoleID, arg.Resource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :execrows
DELETE FROM role_permission WHERE role_id = $1 AND resource = $2 AND permission_id = $3
`

type RevokePermissionFromRoleParams struct {
	RoleID       int32  `json:"roleID"`
	Resource     string `json:"resource"`
	PermissionID int32  `json:"permissionID"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePermissionFromRole, arg.RoleID, arg.Resource, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePermission = `-- name: UpdatePermission :execrows
UPDATE "permission" SET name = $2 WHERE id = $1
`

type UpdatePermissionParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePermission, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
